version: '3'

services:
  app:
    image: shadowreaver/crypto-signal:master
    volumes:
      - ./config.yml:/app/config.yml
    depends_on:
      - flask
  # webhook:
  #   build: .
  #   image: patrickpxp/webhook
  #   volumes:
  #     - ./hooks:/etc/webhook
  #   ports:
  #     - "9000:9000"
  #   command: -hotreload -verbose -hooks=/etc/webhook/hooks.json
  flask:
    build: .
    image: patrickpxp/webhook
    volumes:
      - ./:/app
    ports:
      - "8000:8000"